### ISSUE TITLE
Horrendous media panel with dark gtk themes

### ISSUE THREAD

**Issue by nicman23** [arfbtwn/banshee#53] opened 2017-10-06 12:43 UTC
example pic
![screenshot_20171006_154204](https://user-images.githubusercontent.com/16306097/31278290-11e8c32e-aaad-11e7-864c-bf556e53c4a1.png)

also you cannot see the buttons due to low contrast

**Comment by arfbtwn** [comment] 2017-10-06 22:03
I think it's pretty horrendous on my theme too - at least you can see the track information in the now playing list, the text is white on my system, found the cause of that too though I'm thinking the fix for that might break your display. See #50, I've removed the custom header rendering entirely.

**Comment by arfbtwn** [comment] 2017-10-08 16:46
Resolved with #50

**Closed by arfbtwn** 2017-10-08 16:46 UTC
